services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "banana"
    ports:
      - 15432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

